server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true